platform :ios, '9.0'
use_frameworks!

target 'RCG Personnel' do
pod 'VK-ios-sdk'
pod 'Alamofire', '~> 3.4'
#pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'

end

target 'RCG PersonnelTests' do

end

target 'RCG PersonnelUITests' do

end


